"""ⓘ で出す説明。日本語と英語が1対1で重ならないものだけに付ける。

キーはカードの英語（文は {} を外したもの）。build.py がキーの打ち間違いを検出する。
"""

WORD_NOTES = {
    "backpack": "ランドセルは、オランダ語の ransel（ランセル）から来た言葉。英語では backpack（背中のかばん）と言うよ。",
    "sister": "英語では、お姉さんも妹も sister。区別したいときだけ big sister / little sister と言うよ。",
    "brother": "英語では、お兄さんも弟も brother。区別したいときだけ big brother / little brother と言うよ。",
    "I": "「私」の I は、文のどこにあっても、いつも大文字で書くよ。",
    "mother": "呼ぶときは Mom（マム）と言うことが多いよ。",
    "father": "呼ぶときは Dad（ダッド）と言うことが多いよ。",
    "grandmother": "呼ぶときは Grandma（グランマ）と言うことが多いよ。",
    "grandfather": "呼ぶときは Grandpa（グランパ）と言うことが多いよ。",
    "rice": "お米もご飯も、英語ではどちらも rice。",
    "orange": "オレンジ色の orange は、果物のオレンジからできた言葉。",
    "shoes": "靴は2つで1組だから、最後に s が付いて shoes。",
    "thirteen": "13から19は、最後が teen（ティーン）。だから13〜19歳の人を teenager（ティーンエイジャー）と言うよ。",
    "mouse": "コードがしっぽみたいで、ねずみに似ていたから、マウスと呼ばれるようになったよ。",
    "bug": "昔、コンピューターの中に本物の虫（蛾）が入って動かなくなった、という話が有名。今はプログラムのまちがいを bug と言うよ。",
    "smartphone": "英語では phone（フォン）だけで言うことが多いよ。「スマホ」は日本で縮めた言葉。",
}

PHRASE_NOTES = {
    "Do you want to play soccer?": "Do you want to build a snowman?（雪だるまつくろう）と同じ形。Do you want to 〜? で「〜しない？」とさそえるよ。",
    "Let the balloon go.": "Let it go.（ありのままで）と同じ形。it のところに はなすものを入れると「〜を はなして」。",
    "Let's go into the forest.": "Into the unknown（知らない世界へ）の into。into は「〜の中へ」入っていく動きだよ。",
    "A whole pizza!": "A whole new world（ホール・ニュー・ワールド）の whole。「まるごと・ぜんぶ」の意味だよ。",
    "It's under the bed.": "Under the sea（アンダー・ザ・シー）の under。「〜の下」だよ。",
    "I've got a new friend.": "You've got a friend in me.（君はともだち）の got。I've got 〜 で「〜を持っている・〜ができた」。",
    "I wish I could fly.": "When you wish upon a star（星に願いを）の wish。I wish I could 〜 で「〜できたらいいのに」。",
    "How far is the station?": "How far I'll go（どこまでも）の how far。「どのくらい遠い？」と聞けるよ。",
    "Remember your homework.": "Remember me.（リメンバー・ミー）と同じ形。remember は「おぼえている・わすれない」。",
    "We don't talk in the library.": "We don't talk about Bruno.（秘密のブルーノ）と同じ形。We don't 〜 で「わたしたちは 〜しない」。",
    "Someday I will go to space.": "Someday my prince will come.（いつか王子様が）の someday。「いつか」だよ。",
    "Let it go.": "『アナと雪の女王』の歌。日本語版の題は「ありのままで」。let it go は「手をはなす・もう気にしない」という意味で、ふだんの会話でも使うよ。",
    "Do you want to build a snowman?": "『アナと雪の女王』の歌。日本語版の題は「雪だるまつくろう」。Do you want to 〜? は「〜しない？」とさそう言い方だよ。",
    "Into the unknown": "『アナと雪の女王2』の歌。unknown は「知られていない」。the unknown で「知らない世界」になるよ。",
    "A whole new world": "『アラジン』の歌。whole は「まるごと・ぜんぶ」。a whole new world で「何もかも新しい世界」。",
    "Under the sea": "『リトル・マーメイド』の歌。under は「〜の下」。海の下、つまり 海の中 のことだよ。",
    "You've got a friend in me.": "『トイ・ストーリー』の歌。日本語版の題は「君はともだち」。直訳すると「君は ぼくの中に 友だちを持っている」。英語らしい言い方だね。",
    "When you wish upon a star": "『ピノキオ』の歌。日本語版の題は「星に願いを」。wish は「願う」。",
    "How far I'll go": "『モアナと伝説の海』の歌。how far は「どこまで遠く」。I'll go は「私は行く」。",
    "Remember me.": "『リメンバー・ミー』の歌。映画の題名も この歌の名前から来ているよ。",
    "Beauty and the Beast": "『美女と野獣』の歌。beauty は「美しさ・美しい人」、beast は「けもの」。",
    "We don't talk about Bruno.": "『ミラベルと魔法だらけの家』の歌。日本語版の題は「秘密のブルーノ」。don't talk about 〜 で「〜の話はしない」。",
    "Someday my prince will come.": "『白雪姫』の歌。日本語版の題は「いつか王子様が」。someday は「いつか」。",
    "Let's eat!": "英語には「いただきます」とぴったり同じ言葉はないんだ。食べ始めるときは「Let's eat!（食べよう！）」と言うことが多いよ。作ってくれた人には「Thank you!」。",
    "Hello!": "Hello は朝でも昼でも夜でも使えるよ。「こんにちは」より広い言葉。",
    "Good night.": "寝るときの「おやすみ」と、夜に別れるときに使うよ。夜に会ったときの「こんばんは」は Good evening.",
    "That's OK.": "謝られたときの「いいよ」。「いいよ、やろう！」のいいよは Sure! や OK! だよ。",
    "I'm sorry.": "悪いことをしたときの「ごめんなさい」。人の前を通るときの「すみません」は Excuse me. だよ。",
    "See you!": "また会えるときの「またね」。See you tomorrow! なら「また明日ね」。",
    "Come on!": "Come on! は言い方で意味が変わるよ。「ほら、行こう」「がんばれ」「もう、やめてよ」。",
    "I got it!": "「わかった！」のほかに、ボールを「取った！」ときにも言うよ。",
    "stand up": "up は「上へ」、down は「下へ」。stand up（立つ）と sit down（座る）、pick up（拾う）と put down（置く）。",
    "get up": "wake up は目が覚めること。get up は起き上がって、ふとんから出ること。目が覚めても、まだ get up していないこともあるね。",
    "put on": "日本語は 服を「着る」、帽子を「かぶる」、靴を「はく」、メガネを「かける」と分けるけど、英語は全部 put on。脱ぐ・外すは全部 take off。",
    "turn on": "on は「つながっている・ついている」、off は「はなれている・消えている」。turn on / turn off、put on / take off。",
    "look for": "look at は「見る」、look for は「探す」。for が付くと「〜を求めて」の感じになるよ。",
    "Beef or chicken?": "飛行機のごはん（機内食）で よく聞かれるよ。答えは「Chicken, please.」のように、ほしいほう ＋ please で OK。",
    "Here you are.": "物をわたすときの「はい、どうぞ」。Here you go. も同じ意味だよ。",
    "What's the purpose of your visit?": "国に入るときの質問（入国審査）で聞かれるよ。旅行なら Sightseeing.（観光）と答えればいいんだ。",
    "For here or to go?": "日本の「テイクアウト」は、アメリカでは to go と言うことが多いよ。イギリスでは takeaway。お店で食べるなら For here, please.",
    "Where to?": "Where are you going?（どこへ行くの？）を短くした言い方。タクシーの運転手さんがよく言うよ。",
    "I'm just looking.": "お店の人に話しかけられて、まだ買うか決めていないときに使える、便利な言葉だよ。",
    "Can I have some barley tea?": "麦茶は英語で barley tea（バーリー ティー）。英語を話す国ではあまり飲まないので、通じないこともあるよ。",
    "Can I have a hug?": "hug（ハグ）は、ぎゅっと抱きしめること。英語を話す国では、家族や友だちとよくするよ。",
    "I don't like green peppers.": "ピーマンは、フランス語の piment（ピマン）から来た言葉と言われているよ。英語では green pepper。",
    "Where is Mom?": "お母さんを呼ぶときは Mom。名前みたいに使うから、大文字で始めるよ。Dad も同じ。",
    "Where is the bathroom?": "家でもお店でも、トイレを聞くときは bathroom と言うことが多いよ。",
    "I'm hot.": "自分が暑いときは I'm hot. 天気が暑い・飲み物が熱いときは It's hot. 日本語は「暑い」と「熱い」で漢字が変わるけど、英語はどっちも hot。",
    "It's hot.": "天気が暑い・飲み物が熱いときは It's hot. 自分が暑いときは I'm hot. 日本語は「暑い」と「熱い」で漢字が変わるけど、英語はどっちも hot。",
}
