"""えいごでいおう の文。{} でかこんだところが、えで入れかわる語。"""

PHRASE_PAGES = [
    ("あいさつ", [
        ("☀️", "Good morning.", "おはよう"), ("🌙", "Good night.", "おやすみ"),
        ("🖐️", "Hello!", "こんにちは"), ("👋", "See you!", "またね"),
        ("🙏", "Thank you.", "ありがとう"), ("😊", "You're welcome.", "どういたしまして"),
        ("🙇", "I'm sorry.", "ごめんなさい"), ("🆗", "That's OK.", "いいよ"),
        ("🍽️", "Let's eat!", "いただきます"), ("❓", "What's this?", "これなあに？"),
        ("🆘", "Help me!", "たすけて"), ("🎂", "Happy birthday!", "おたんじょうび おめでとう"),
    ]),
    ("すき I like", [
        ("🍎", "I like {apples}.", "りんごがすき"), ("🍌", "I like {bananas}.", "バナナがすき"),
        ("🐱", "I like {cats}.", "ねこがすき"), ("🐶", "I like {dogs}.", "いぬがすき"),
        ("🍰", "I like {cake}.", "ケーキがすき"), ("🍦", "I like {ice cream}.", "アイスがすき"),
        ("🚃", "I like {trains}.", "でんしゃがすき"), ("📖", "I like {books}.", "ほんがすき"),
        ("🎮", "I like {games}.", "ゲームがすき"), ("🏊", "I like {swimming}.", "およぐのがすき"),
        ("🎵", "I like {music}.", "おんがくがすき"), ("🐧", "I like {penguins}.", "ペンギンがすき"),
    ]),
    ("きらい I don't like", [
        ("🕷️", "I don't like {spiders}.", "くもはきらい"), ("🐛", "I don't like {bugs}.", "むしはきらい"),
        ("🌧️", "I don't like {rain}.", "あめはきらい"), ("🥕", "I don't like {carrots}.", "にんじんはきらい"),
        ("🍅", "I don't like {tomatoes}.", "トマトはきらい"), ("🫑", "I don't like {green peppers}.", "ピーマンはきらい"),
        ("⚡", "I don't like {thunder}.", "かみなりはきらい"), ("🐍", "I don't like {snakes}.", "へびはきらい"),
        ("💉", "I don't like {shots}.", "ちゅうしゃはきらい"), ("🌑", "I don't like {the dark}.", "くらいのはきらい"),
        ("🔊", "I don't like {loud noises}.", "おおきいおとはきらい"), ("👻", "I don't like {ghosts}.", "おばけはきらい"),
    ]),
    ("きもち I'm", [
        ("😄", "I'm {happy}.", "うれしい"), ("😢", "I'm {sad}.", "かなしい"),
        ("😠", "I'm {angry}.", "おこってる"), ("🤤", "I'm {hungry}.", "おなかすいた"),
        ("😪", "I'm {sleepy}.", "ねむい"), ("😩", "I'm {tired}.", "つかれた"),
        ("🥵", "I'm {hot}.", "あつい"), ("🥶", "I'm {cold}.", "さむい"),
        ("😱", "I'm {scared}.", "こわい"), ("🤩", "I'm {excited}.", "わくわくする"),
        ("🥱", "I'm {bored}.", "たいくつ"), ("🤒", "I'm {sick}.", "ぐあいがわるい"),
    ]),
    ("したい I want to", [
        ("🎲", "I want to {play}.", "あそびたい"), ("🍽️", "I want to {eat}.", "たべたい"),
        ("😴", "I want to {sleep}.", "ねたい"), ("🏠", "I want to {go home}.", "おうちにかえりたい"),
        ("🏊", "I want to {swim}.", "およぎたい"), ("📖", "I want to {read a book}.", "ほんをよみたい"),
        ("🎨", "I want to {draw a picture}.", "えをかきたい"), ("📺", "I want to {watch TV}.", "テレビをみたい"),
        ("🛝", "I want to {go to the park}.", "こうえんにいきたい"), ("🛁", "I want to {take a bath}.", "おふろにはいりたい"),
        ("👵", "I want to {see Grandma}.", "おばあちゃんにあいたい"), ("🚲", "I want to {ride a bike}.", "じてんしゃにのりたい"),
    ]),
    ("ちょうだい Can I have", [
        ("💧", "Can I have {some water}?", "おみずちょうだい"), ("🥛", "Can I have {some milk}?", "ぎゅうにゅうちょうだい"),
        ("🧃", "Can I have {some juice}?", "ジュースちょうだい"), ("🍪", "Can I have {a cookie}?", "クッキーちょうだい"),
        ("🍌", "Can I have {a banana}?", "バナナちょうだい"), ("🍬", "Can I have {some candy}?", "あめちょうだい"),
        ("🍞", "Can I have {some bread}?", "パンちょうだい"), ("🍚", "Can I have {some rice}?", "ごはんちょうだい"),
        ("➕", "Can I have {one more}?", "もうひとつちょうだい"), ("🤗", "Can I have {a hug}?", "ぎゅってして"),
        ("🤧", "Can I have {a tissue}?", "ティッシュちょうだい"), ("✏️", "Can I have {a pencil}?", "えんぴつちょうだい"),
    ]),
    ("しよう Let's", [
        ("🎲", "Let's {play a game}!", "ゲームしよう"), ("🚶", "Let's {go}!", "いこう"),
        ("🎤", "Let's {sing}!", "うたおう"), ("💃", "Let's {dance}!", "おどろう"),
        ("🏃", "Let's {run}!", "はしろう"), ("🍳", "Let's {cook}!", "りょうりしよう"),
        ("🎨", "Let's {draw}!", "えをかこう"), ("📸", "Let's {take a picture}!", "しゃしんをとろう"),
        ("🧱", "Let's {build something}!", "なにかつくろう"), ("🔍", "Let's {look for it}!", "さがそう"),
        ("🍿", "Let's {watch a movie}!", "えいがをみよう"), ("🛏️", "Let's {go to bed}!", "ねよう"),
    ]),
    ("できる I can", [
        ("🏊", "I can {swim}.", "およげる"), ("🏃‍♀️", "I can {run fast}.", "はやくはしれる"),
        ("🦘", "I can {jump high}.", "たかくとべる"), ("🚲", "I can {ride a bike}.", "じてんしゃにのれる"),
        ("🍳", "I can {cook}.", "りょうりできる"), ("🔟", "I can {count to ten}.", "10までかぞえられる"),
        ("✍️", "I can {write my name}.", "なまえがかける"), ("🎤", "I can {sing}.", "うたえる"),
        ("🤸", "I can {do a cartwheel}.", "そくてんできる"), ("👟", "I can {tie my shoes}.", "くつひもがむすべる"),
        ("🔤", "I can {read English}.", "えいごがよめる"), ("🧩", "I can {do puzzles}.", "パズルができる"),
    ]),
    ("どこ Where is", [
        ("🎒", "Where is {my bag}?", "わたしのかばんどこ？"), ("👟", "Where are {my shoes}?", "わたしのくつどこ？"),
        ("🐱", "Where is {the cat}?", "ねこはどこ？"), ("👩", "Where is {Mom}?", "おかあさんはどこ？"),
        ("👨", "Where is {Dad}?", "おとうさんはどこ？"), ("🚽", "Where is {the bathroom}?", "トイレはどこ？"),
        ("✏️", "Where is {my pencil}?", "わたしのえんぴつどこ？"), ("⚽", "Where is {the ball}?", "ボールはどこ？"),
        ("🔑", "Where is {the key}?", "かぎはどこ？"), ("📖", "Where is {my book}?", "わたしのほんどこ？"),
        ("🚉", "Where is {the station}?", "えきはどこ？"), ("🧸", "Where is {my teddy bear}?", "わたしのくまのぬいぐるみどこ？"),
    ]),
    ("〜だね It's", [
        ("🔥", "It's {hot}.", "あついね"), ("❄️", "It's {cold}.", "さむいね"),
        ("🐘", "It's {big}.", "おおきいね"), ("🐜", "It's {small}.", "ちいさいね"),
        ("🐰", "It's {cute}.", "かわいいね"), ("😋", "It's {yummy}.", "おいしいね"),
        ("👻", "It's {scary}.", "こわいね"), ("🤣", "It's {funny}.", "おもしろいね"),
        ("🌸", "It's {beautiful}.", "きれいだね"), ("🚀", "It's {fast}.", "はやいね"),
        ("🏋️", "It's {heavy}.", "おもいね"), ("🌧️", "It's {raining}.", "あめがふってるね"),
    ]),
]
